server.port=9000
spring.main.banner-mode=off
spring.main.allow-circular-references=true
spring.jpa.open-in-view=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# WebSocket configuration
spring.websocket.max-text-message-size=8192
spring.websocket.max-binary-message-size=8192

# Actuator configuration
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Logging configuration
logging.level.org.springframework=INFO
logging.level.com.richashworth.planningpoker=DEBUG
