language: java

jdk:
- oraclejdk8

env:
- NODE_VERSION=6

install:
- nvm install $NODE_VERSION
- nvm use $NODE_VERSION
- sudo apt-get install -y curl
- curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
- sudo apt-get install -y nodejs
- sudo npm install -g yarn
- wget https://cli-assets.heroku.com/branches/stable/heroku-linux-amd64.tar.gz
- tar -xf heroku-linux-amd64.tar.gz

script:
- ./gradlew
- ./heroku/bin/heroku plugins:install heroku-cli-deploy
- ./heroku/bin/heroku jar:deploy planningpoker-api/build/libs/*.jar --app planningpoker-tool HEROKU_API_KEY

after_success:
- bash <(curl -s https://codecov.io/bash)
