version: '2'

services:
  api:
    build:
      context: ./planningpoker-api
      dockerfile: Dockerfile
    ports:
    - "9000:9000"
  web:
    volumes:
    - '.:/usr/src/app'
    - /usr/src/app/node_modules'
    build:
      context: ./planningpoker-web
      dockerfile: Dockerfile
    ports:
    - "8080:3000"
