version: '2'

services:
  server:
    build: .
    ports:
    - "9000:9000"
  ui:
    volumes:
    - '.:/usr/src/app'
    - /usr/src/app/node_modules'
    build:
      context: ./planningpoker-client
      dockerfile: Dockerfile
    ports:
    - "8080:3000"
